import io
import json
import os
from pathlib import Path
import re
import subprocess

try:
    import markdown
    MARKDOWN_AVAILABLE = True
except ImportError:
    MARKDOWN_AVAILABLE = False

def updateSiteIndex(siteIndexPath, guideEntries):
    with io.open(siteIndexPath, 'r') as f:
        inText = f.read()

    # Preserve the comment header
    commentMatch = re.match(r"((?:\/\/[^\n]*\n)*)", inText)
    comments = commentMatch.group(1) if commentMatch else ""

    # Extract and parse the JSON array
    match = re.search(r"const siteIndex = ([\s\S]+)", inText)
    jsonText = match.group(1).rstrip().rstrip(';')
    siteIndex = json.loads(jsonText)

    # Remove any existing Guides section
    siteIndex = [entry for entry in siteIndex if entry.get("name") != "Guides"]

    # Insert new Guides section before Appendix (if any guides exist)
    if guideEntries:
        guidesSection = {
            "name": "Guides",
            "children": guideEntries
        }
        appendixIdx = next((i for i, e in enumerate(siteIndex) if e.get("name") == "Appendix"), -1)
        if appendixIdx >= 0:
            siteIndex.insert(appendixIdx, guidesSection)
        else:
            siteIndex.append(guidesSection)

    with io.open(siteIndexPath, 'w') as f:
        f.write(comments + "const siteIndex = " + json.dumps(siteIndex, indent=4))

def generateGuides(repoRoot, dataPath, usePerforce):
    if not MARKDOWN_AVAILABLE:
        print("NOTE: python-markdown is not installed. Guides feature is disabled.")
        print("      Install with: pip install markdown")
        return True

    guidesJsonPath = Path(repoRoot) / "contrib" / "guides.json"
    guidesSrcPath = Path(repoRoot) / "contrib" / "guides"
    guidesOutputPath = Path(repoRoot) / "guides"
    templatePath = Path(dataPath) / "guide-template.html"
    siteIndexPath = Path(dataPath) / "siteindex.js"

    guides = []
    if guidesJsonPath.exists():
        with io.open(guidesJsonPath, 'r') as f:
            guides = json.loads(f.read())
    else:
        print(f"NOTE: {guidesJsonPath} not found. No guides to generate.")

    if not templatePath.exists():
        print(f"ERROR: guide-template.html does not exist at {templatePath}")
        return False

    with io.open(templatePath, 'r') as f:
        template = f.read()

    guidesOutputPath.mkdir(exist_ok=True)

    if usePerforce:
        p4EditString = str(siteIndexPath.name) + " "
        p4AddString = ""
        for guide in guides:
            slug = Path(guide["filename"]).stem
            htmlPath = guidesOutputPath / f"{slug}.html"
            if htmlPath.exists():
                p4EditString += htmlPath.name + " "
            else:
                p4AddString += htmlPath.name + " "
        if p4EditString.strip():
            subprocess.run("p4 edit " + p4EditString, check=True, shell=True, cwd=dataPath)
        if p4AddString.strip():
            subprocess.run("p4 add " + p4AddString, check=True, shell=True, cwd=str(guidesOutputPath))

    sidebarEntries = []
    for guide in guides:
        filename = guide.get("filename", "")
        title = guide.get("title", "")
        description = guide.get("description", "")
        author = guide.get("author", "")

        if not filename or not title:
            print(f"WARNING: Guide entry is missing 'filename' or 'title', skipping.")
            continue

        mdPath = guidesSrcPath / filename
        if not mdPath.exists():
            print(f"WARNING: Guide source file {mdPath} not found, skipping.")
            continue

        with io.open(mdPath, 'r', encoding='utf-8') as f:
            mdText = f.read()

        content = markdown.markdown(mdText, extensions=['tables', 'fenced_code'])

        meta = ""
        if author:
            meta += f'<p class="guide-author">By {author}</p>\n'
        if description:
            meta += f'<p class="guide-description">{description}</p>\n'

        slug = Path(filename).stem
        htmlContent = template.replace("<##>", title).replace("<@@>", meta + content)

        outputPath = guidesOutputPath / f"{slug}.html"
        with io.open(outputPath, 'w', encoding='utf-8') as f:
            f.write("<!-- Generated by generate-guides.py -->\n" + htmlContent)

        sidebarEntries.append({
            "name": title,
            "path": f"/guides/{slug}.html"
        })

    updateSiteIndex(siteIndexPath, sidebarEntries)

    if usePerforce:
        subprocess.run("p4 revert -a -c default", check=True, shell=True, cwd=dataPath)
        if guidesOutputPath.exists():
            subprocess.run("p4 revert -a -c default", check=True, shell=True, cwd=str(guidesOutputPath))

    return True
