import io
import json
import os
from pathlib import Path
import subprocess

def generateCommunityNotes(repoRoot, dataPath, usePerforce):
    outputPath = Path(os.path.join(dataPath, "community-notes.js"))
    contribPath = Path(os.path.join(repoRoot, "contrib", "community-notes.json"))

    if usePerforce:
        p4EditString = ""
        p4AddString = ""
        if os.path.exists(outputPath):
            p4EditString = outputPath.name
        else:
            p4AddString = outputPath.name
        if p4EditString:
            subprocess.run("p4 edit " + p4EditString, check=True, shell=True, cwd=dataPath)
        if p4AddString:
            subprocess.run("p4 add " + p4AddString, check=True, shell=True, cwd=dataPath)

    notes = []
    if os.path.exists(contribPath):
        with io.open(contribPath, 'r') as f:
            notes = json.loads(f.read())
    else:
        print(f"NOTE: {contribPath} not found, writing empty community notes.")

    with io.open(outputPath, 'w') as f:
        output = (
            "// Generated by generate-community-notes.py\n"
            "// To let users open the HTML files directly without a local server, we need to eliminate any CORS requests like \"fetch\".\n"
            "// Workaround is to place json into .js files and then load them via html script tags.\n"
            "// https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp\n"
            "const communityNotes = " + json.dumps(notes, indent=4)
        )
        f.write(output)

    if usePerforce:
        subprocess.run("p4 revert -a -c default", check=True, shell=True, cwd=dataPath)

    return True
